package exception;

import java.util.Scanner;

public class FinallyRunner {

	public static void main(String[] args) {
		try {
			Scanner sc = new Scanner(System.in);
			int[] numbers = { 12, 3, 4, 5 };
			int number = numbers[5];

			System.out.println("Before Scanner Close");
			sc.close();
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

}
